# Generated by Django 2.2.6 on 2019-11-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_hello',
            field=models.BooleanField(default=False, verbose_name='developm'),
        ),
    ]
