# Generated by Django 2.2.6 on 2019-10-25 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectID', models.CharField(max_length=4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('right', models.CharField(max_length=3)),
                ('projectID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Pbi',
            fields=[
                ('title', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=1)),
                ('description', models.CharField(max_length=2000)),
                ('priority', models.DecimalField(decimal_places=0, max_digits=4)),
                ('storyPt', models.DecimalField(decimal_places=0, max_digits=2)),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Project')),
            ],
        ),
    ]
