# Generated by Django 2.2.6 on 2019-12-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbi',
            name='status',
            field=models.CharField(choices=[('Not Started(*)', 'Not Started(*)'), ('In Progress(*)', 'In Progress(*)'), ('Completed', 'Completed')], default='Not Started', max_length=20),
        ),
    ]
