# Generated by Django 2.2.6 on 2019-10-25 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbi',
            name='projectID',
            field=models.ForeignKey(default='A', on_delete=django.db.models.deletion.CASCADE, to='orders.Project'),
        ),
    ]
