# Generated by Django 2.2.6 on 2019-12-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191204_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
