# Generated by Django 2.2.6 on 2019-11-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_sprint_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active Sprint'),
        ),
    ]
