# Generated by Django 2.2.6 on 2019-11-07 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_user_is_hello'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_hello',
        ),
    ]
