# Generated by Django 2.2.6 on 2019-11-08 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191026_0321'),
        ('orders', '0002_auto_20191108_1856'),
        ('orders', '0003_remove_user_is_hello'),
    ]

    operations = [
    ]
