# Generated by Django 2.2.6 on 2019-12-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='project',
            field=models.ManyToManyField(to='orders.Project'),
        ),
    ]
